import { i18nBuilder } from "keycloakify/login";
import type { ThemeName } from "../kc.gen";

/** @see: https://docs.keycloakify.dev/i18n */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const { useI18n, ofTypeI18n } = i18nBuilder
    .withThemeName<ThemeName>()
    .withCustomTranslations({
        en: {
            "or-login-with-email": "Or sign in with your email",
            // login-username.ftl
            "login-with-proconnect": "Sign in with ProConnect",
            "proconnect-description":
                "ProConnect is the solution provided by the State to secure and simplify sign-in to online services.",
            "what-is-proconnect": "What is ProConnect?",
            "login-with-email-title": "Sign in with your email address",
            "email-format-hint": "Expected format: name@domain.fr",
            // mail-otp-form.ftl / otp-choice.ftl (keys mirrored from the mail-otp-authenticator extension)
            codeSentByMail: "A code has been sent to your mailbox.<br>Please report it below:",
            otpChoiceTitle: "One-time code choice",
            otpChoiceDescription: "Please choose below how you will obtain your one-time code.",
            otpChoiceApp: "One-time code generated by a mobile app",
            otpChoiceAppDescription:
                "You will get the requested code from a mobile app that you will set up in the next step.",
            otpChoiceMail: "One-time code sent by email",
            otpChoiceMailDescription: "An email containing a one-time code to copy will be sent to you when you sign in.",
            // mail-otp-form.ftl (UI)
            "mail-otp-title": "One-time code sent",
            "mail-otp-code-info": "An authentication code valid for {0} minutes has been sent by email to: {1}",
            "mail-otp-your-email": "your email address",
            "mail-otp-code-label": "6-digit code",
            "mail-otp-code-hint": "Expected format: 094532",
            "mail-otp-resend": "Resend a code",
            "mail-otp-validate": "Submit"
        },
        fr: {
            "or-login-with-email": "Ou connectez-vous avec votre email",
            // login-username.ftl
            "login-with-proconnect": "Se connecter avec ProConnect",
            "proconnect-description":
                "ProConnect est la solution proposée par l’État pour sécuriser et simplifier la connexion aux services en ligne.",
            "what-is-proconnect": "Qu’est-ce que ProConnect ?",
            "login-with-email-title": "Se connecter avec son adresse électronique",
            "email-format-hint": "Format attendu : nom@domaine.fr",
            // mail-otp-form.ftl / otp-choice.ftl (clés alignées sur l'extension mail-otp-authenticator)
            codeSentByMail: "Un code vous a été envoyé par email.<br>Recopiez-le dans le champ ci-dessous :",
            otpChoiceTitle: "Choix du code à usage unique",
            otpChoiceDescription:
                "<p>Pour plus de sécurité, il vous sera demandé de renseigner un code à usage unique quand vous vous connecterez à l’application.</p><p>Choisissez ci-dessous le moyen qui sera utilisé pour obtenir ce code.</p>",
            otpChoiceApp: "Code unique généré via application mobile",
            otpChoiceAppDescription:
                "Vous pourrez obtenir le code demandé à partir d’une application mobile que vous allez configurer à l’étape suivante.",
            otpChoiceMail: "Code unique envoyé par email",
            otpChoiceMailDescription: "Un email contenant un code unique à recopier vous sera envoyé à la connexion.",
            // mail-otp-form.ftl (UI)
            "mail-otp-title": "Envoi d’un code à usage unique",
            "mail-otp-code-info": "Un code d’authentification valable {0} minutes a été envoyé par email à l’adresse suivante : {1}",
            "mail-otp-your-email": "votre adresse email",
            "mail-otp-code-label": "Code à 6 chiffres",
            "mail-otp-code-hint": "Format attendu : 094532",
            "mail-otp-resend": "Renvoyer un code",
            "mail-otp-validate": "Valider"
        }
    })
    .build();

type I18n = typeof ofTypeI18n;

export { useI18n, type I18n };
